// ============================================================
// COMPLIANCE REPORT GENERATOR (prototype)
// Turns a screening result into a formal, self-contained report
// a fintech can save, print, or hand to a regulator/auditor.
// ------------------------------------------------------------
// Output: a printable HTML document opened in a new window
// (user can Save as PDF via the browser print dialog).
// Future: server-side signed PDFs, tamper-evident hashes,
// regulator-specific formats (UIF, COAF, UIAF filings).
// ============================================================

function esc(s){ return String(s).replace(/[&<>]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])); }

const VERDICT_TEXT = {
  pass:   { label: "APPROVED",            note: "All applied rules satisfied — transfer may proceed." },
  review: { label: "ROUTED TO REVIEW",    note: "Flagged rules require a human analyst decision before release." },
  block:  { label: "BLOCKED",             note: "A hard rule failed — transfer cannot proceed as submitted." },
};

export function buildReport({ country, authorities, amount, rail, purpose, kyc, verdict, checks }){
  const now = new Date();
  const ref = "CR-" + now.getTime().toString(36).toUpperCase();
  const v = VERDICT_TEXT[verdict] || VERDICT_TEXT.review;

  const rows = checks.map(c=>{
    const mark = c.status==='ok' ? "PASS" : c.status==='fail' ? "FAIL" : "FLAG";
    return `<tr>
      <td class="mk mk-${c.status}">${mark}</td>
      <td>${esc(c.title)}</td>
      <td class="basis">${esc(c.basis)}</td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Compliance Report ${ref}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:Georgia,'Times New Roman',serif;color:#12211c;line-height:1.5;
    max-width:760px;margin:0 auto;padding:40px 30px}
  .hd{display:flex;justify-content:space-between;align-items:flex-start;
    border-bottom:2px solid #12211c;padding-bottom:14px;margin-bottom:22px}
  .hd .brand{font-size:22px;font-weight:700}
  .hd .brand span{color:#1f7a4d}
  .hd .meta{text-align:right;font-size:12px;color:#555;font-family:ui-monospace,monospace}
  h1{font-size:16px;margin:0 0 4px}
  .sub{color:#555;font-size:13px;margin-bottom:20px}
  .verdict{border:2px solid;border-radius:4px;padding:14px 16px;margin-bottom:24px}
  .v-pass{border-color:#1f7a4d;background:#e6f1e9}
  .v-review{border-color:#9a6a12;background:#f5ecd8}
  .v-block{border-color:#a8321f;background:#f6e7e2}
  .verdict .vl{font-size:15px;font-weight:700;letter-spacing:.5px}
  .verdict .vn{font-size:13px;color:#333;margin-top:2px}
  table{width:100%;border-collapse:collapse;margin:14px 0 24px;font-size:13px}
  th{text-align:left;border-bottom:1px solid #12211c;padding:6px 8px;font-size:11px;
    text-transform:uppercase;letter-spacing:.4px;color:#555}
  td{padding:7px 8px;border-bottom:1px solid #ddd;vertical-align:top}
  .mk{font-family:ui-monospace,monospace;font-size:11px;font-weight:700;width:52px}
  .mk-ok{color:#1f7a4d}.mk-fail{color:#a8321f}.mk-flag{color:#9a6a12}
  .basis{color:#555;font-size:12px}
  .params{width:100%;font-size:13px;margin-bottom:8px;border-collapse:collapse}
  .params td{padding:4px 8px;border:none}
  .params td:first-child{color:#555;width:150px}
  .foot{margin-top:30px;padding-top:14px;border-top:1px solid #ddd;
    font-size:11px;color:#777;line-height:1.6}
  @media print{body{padding:0}.noprint{display:none}}
  .noprint{margin-bottom:20px}
  .btn{font:inherit;font-size:13px;font-weight:600;padding:8px 16px;border:1px solid #12211c;
    background:#12211c;color:#fff;border-radius:3px;cursor:pointer}
</style></head><body>
  <div class="noprint"><button class="btn" onclick="window.print()">Save as PDF / Print</button></div>
  <div class="hd">
    <div class="brand">Corre<span>dor</span></div>
    <div class="meta">Report ${ref}<br>${now.toISOString()}</div>
  </div>
  <h1>Cross-Border Compliance Screening Report</h1>
  <div class="sub">Corridor: United States → ${esc(country)} · Rulebook: ${esc(authorities)}</div>

  <div class="verdict v-${verdict}">
    <div class="vl">${v.label}</div>
    <div class="vn">${v.note}</div>
  </div>

  <table class="params">
    <tr><td>Amount</td><td>$${Number(amount).toLocaleString()} USD</td></tr>
    <tr><td>Rail</td><td>${rail==='stablecoin'?'Stablecoin (USDC)':'Bank wire'}</td></tr>
    <tr><td>Purpose</td><td>${esc(purpose.replace('_',' '))}</td></tr>
    <tr><td>Recipient KYC</td><td>${esc(kyc)}</td></tr>
  </table>

  <table>
    <thead><tr><th>Result</th><th>Rule</th><th>Basis</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="foot">
    Generated by Corredor — prototype cross-border compliance engine. Rules are a starter
    subset of 2026 regulation and this document is not legal advice. For a real filing,
    verify against primary sources (e.g. Mexico: sppld.sat.gob.mx; Brazil: bcb.gov.br;
    Colombia/Argentina: UIAF / CNV) and a qualified compliance professional.
  </div>
</body></html>`;
}

export function openReport(data){
  const html = buildReport(data);
  const w = window.open('', '_blank');
  if(w){ w.document.write(html); w.document.close(); }
}
